version: "3.4"
services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DATABASE: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  api:
    image: node:10-alpine
    command: npm start
    depends_on:
      - postgresql
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    working_dir: /app
volumes:
  data:
    driver: local

